### ISSUE TITLE
Create a radius filter file

### ISSUE THREAD

**Issue by FebruaryRain** [FebruaryRain/PostcodeCrimeChecker#10]
`As the program, I want to be able to filter the records retrieved from the crime data files according to if they fall within the user-defined radius, so that I can required data for report generation.`

@roksolana-15  (SAM can help)

The data we retrieve from the files needs to be filtered for if it falls within our radius. If it doesn't, we need to ignore it. If it does, we will want to pass it on to the next stage of the program.

 - [x] Create a module for this to fit in (`radius_filter.py`?)
 - [x] Write an algorithm for the radius filter
 - [x] Discard (ignore) rows which aren't within the user-defined radius
 - [x] Add the rows which do fall in the user-defined radius to another list which we can pass on to the next stage
 - [x] Test and add docs

Note, we want to send to the next stage only 1 list, as this will be simplest for the next person down the chain to deal with.

**Comment by roksolana-15** [comment]
@FebruaryRain

**Comment by FebruaryRain** [comment]
Confirmed
