### ISSUE TITLE
Create Sort by Date algorithm 

### ISSUE THREAD

**Issue by FebruaryRain** [FebruaryRain/PostcodeCrimeChecker#13]
`As the program,  I want to be able to sort the data by date, if specified, to do so in order that I can pass on correctly sorted data to the next module`

 - [x] Create an algorithm to sort by date
 - [x] Test

**Comment by FebruaryRain** [comment]
Relates to #11 - Create sorting file for report (EPIC)

**Comment by roksolana-15** [comment]
@FebruaryRain

**Comment by FebruaryRain** [comment]
Confirmed
