### ISSUE TITLE
Create overarching logic for the sort report file

### ISSUE THREAD

**Issue by FebruaryRain** [FebruaryRain/PostcodeCrimeChecker#15]
`As the program, I want to be able to correctly apply the right logic for sorting data so that I can create correctly sorted reports.`

This module should take the following form:
 - [x] Assess the user-defined option (with a default "nothing" argument if none specified).
 - [x] Use a mechanism to get the correct algorithm to be enacted
 - [x] Then return the correctly sorted data, ready for the next item down the chain
 - [x] Test the logic with test cases.

**Comment by FebruaryRain** [comment]
Relates to #11 - Create sorting file for report (EPIC)

**Comment by roksolana-15** [comment]
@FebruaryRain

**Comment by FebruaryRain** [comment]
Confirmed
