### ISSUE TITLE
Only EX postcodes are valid

### ISSUE THREAD

**Issue by FebruaryRain** [FebruaryRain/PostcodeCrimeChecker#17]
`As the program, I only want to consider EX postcodes valid, so that I fulfill the specification.`

The specification states that only EX postcodes are to be accepted.
This requires multi-level cooperation.
JAMES - in the UI, we must have validation that the Postcode submitted by the user is an EX one.
SAM - We must filter data from postcodes for only the ones which start with EX, any others allowed to slip through may cause an error.

**Comment by FebruaryRain** [comment]
This is something which can be covered on my end in issue #23 as we will only have EX postcodes in the file we ultimately go to, if the proposed extra program is approved.

**Comment by Jamespurple** [comment]
@FebruaryRain

**Comment by FebruaryRain** [comment]
Limited functionality implemented but to brief. Accepted as closed.
