### ISSUE TITLE
Add Error handling for when an invalid Postcode is submitted

### ISSUE THREAD

**Issue by FebruaryRain** [FebruaryRain/PostcodeCrimeChecker#18]
`As the program, I want to be able to securely handle when an invalid postcode is inputted, so that I can continue to ask again for a centre postcode`

#17 sparked this off.
As we are only accepting EX postcodes, we must have a validation and error handling capability. 
JAMES - This is something to do, I can work on the logic with you if needed.

**Comment by FebruaryRain** [comment]
This will also be covered in issue #25

**Comment by FebruaryRain** [comment]
Note, the length of the postcodes is always 7, though as discussed in issue #26, we must accept the user's postcode of 6 or 7 characters for later transformation into something useful.

**Comment by Jamespurple** [comment]
@FebruaryRain

**Comment by FebruaryRain** [comment]
This has been implemented. Further implementation logic for 6 char postcodes added by @FebruaryRain.
