### ISSUE TITLE
Add logic to ensure that postcodes are handled from user input correctly

### ISSUE THREAD

**Issue by FebruaryRain** [FebruaryRain/PostcodeCrimeChecker#26]
`As the user, I want my postcode inputs to be handled correctly when I conform to the program's rules on input`

Relates to issues #25 and #18 
We want to force the user to user only alphanumeric characters, so we need to handle their postcode entries correctly, therefore::
 - If there are only alphanumeric chars allowed, that means there can never be any whitespaces.
***********************************
So we will have to:
 - [x] Warn the User of this (in the UI)
 - [x] The logic for looking up postcodes needs creating, as there is whitespace in the postcodes. Luckily, we can take advantage of:
    - All postcodes are 7 chars long. 
    - If the postcode is of format "EX1 0PL" (two numbers in the middle), we can simply split the list in two at the midpoint and create a new string to use
    - If the postcode is of format "EX116JT" (three numbers) the we need not split.
    - This can all be done by asking the user to input the string with no spaces, telling them to go again if there is one, then assessing the length of their return.

**Comment by Jamespurple** [comment]
@FebruaryRain

**Comment by FebruaryRain** [comment]
Confirmed
