### ISSUE TITLE
Removing function distance_to_1_dp 

### ISSUE THREAD

**Issue by roksolana-15** [FebruaryRain/PostcodeCrimeChecker#27]
Removing the the distance_to_1_dp function in order to make the postcodes within distance more accurate.
Could alternatively make one that rounds down so that distances such as 5.04km isn't rounded to 5.0km and not included in our report for crimes within 5km.

**Comment by FebruaryRain** [comment]
The solution we would actually want is round up to 1dp. 
I have removed the function in question.
@roksolana-15 , if you want a function to round in the way you describe I can do that but please create a new issue and stick it in my name once you have decided to do so as the logic to do this is simple enough that you can probably do it yourself in packaging the end data for Samir.
