### ISSUE TITLE
Amend cls()

### ISSUE THREAD

**Issue by FebruaryRain** [FebruaryRain/PostcodeCrimeChecker#28]
`As the program, I want to clean the display such that the user won't become confused, in order to aid in the smooth use of the application`

Presently, the cls() (clear last screen) program looks like this:
```def cls():
    print("\n" * 100)
```
My thoughts now are:
 - [x] The \n * 100 is a bit much, can make do with more like 50 I think - have a play with it in a console and see the minimum number of lines.
 - [x] Also, expand on the name; cls isn't especially expressive (though I did get it meant "clear last screen" after pondering it for a while).
 - [x] On further reflection, we might even not clear the screen entirely, but rather do something like `print("\n"*10+"***************************")` to act as a discernible break between inputs and screen, thus error messages will be shown.
Feel free to kick back on this if you have something else in mind, however.

**Comment by Jamespurple** [comment]
@FebruaryRain

**Comment by FebruaryRain** [comment]
Confirmed
