### ISSUE TITLE
UI must not allow default values through

### ISSUE THREAD

**Issue by FebruaryRain** [FebruaryRain/PostcodeCrimeChecker#31]
`As the program, I want only correct values and no defaults to be passed on, in order that the program will successfully execute.`

Presently, the default values can be passed through. We must not allow this as they are not valid.
 - [x] Create a method for assessing that each of the arguments are valid (in the confirm section of the UI?)
 - [x] Be able to break out of the confirm section (Superceded by different implementation)
 - [x] Ideally, inform the user which value is incorrect.

**Comment by Jamespurple** [comment]
@FebruaryRain

**Comment by FebruaryRain** [comment]
Confirmed
